dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: robot_provide
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://47.84.225.001:2181
  metadata-report:
    address: zookeeper://47.84.225.001:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20888
  version: 1.0.0
  scan:
    base-packages: org.dromara.soul.dubbo.service  #服务暴露与发现消费所在的package
#  scan:
#    base-packages: org.dromara.soul.dubbo.service
soul:
  # Soul 针对 Dubbo 的配置项，对应 DubboConfig 配置类
  dubbo:
    admin-url: http://127.0.0.1:9095 # Soul Admin 地址
    context-path: /user # 设置在 Soul 网关的路由前缀，例如说 /order、/product 等等。
    # 后续，网关会根据该 context-path 来进行路由
    app-name: user # 应用名。未配置情况下，默认使用 Dubbo 的应用名
spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 5050